#!/usr/bin/env sh

function installBrew() {
	ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
}

# Install Homebrew
if test ! $(which brew)
then
	echo "Installing Homebrew.."
	installBrew
else
	echo "Homebrew found. Going on.."
fi

# Update Homebrew
brew update

# Install brews
install_homebrew_core_tools

# Install casks
install_homebrew_casks

# Set standard settings
source 'settings.sh'
source 'symlink-dotfiles.sh'

# Update OS X
sudo softwareupdate -i -a