#!/usr/bin/env sh

# Installs some usefull things using Homebrew

# a = brew('list').replace('\t', '').replace('\n', ' ').split()
# b = str(cat('/Users/wolf/.dotfiles/osx/configure/install_homebrew_core_tools.sh')).split()
# for i in a:
#     print str(i) in b, str(i)

function installThings() {
	# Make sure we’re using the latest Homebrew
	echo "Updating.."
	brew update

	# Upgrade any already-installed formulae
	brew upgrade

	# install some dependencies
	brew install gdbm --universal
	brew install sqlite --universal
	brew install libsndfile

	brew install git

	brew install zsh tmux
	brew install fish
	brew install heroku-toolbelt

	brew install smlnj
	brew install rust
	brew install node
	brew install go

	brew install osxfuse
	brew install ntfs-3g

	brew install emacs
	brew install ncdu
	brew install dfc
	brew install z
	brew install trash
	brew install submarine
	brew install ranger
	brew install pstree
	berw install media-info

	brew install mitmproxy

	brew install binutils

	brew install pv
	brew install ninja
	brew install xctool

	brew install gh
	brew install mongodb

	brew tap telemachus/homebrew-desc && brew install brew-desc

	brew install grc

	brew install appledoc

	# Web tools
	brew install wget --enable-iri
	brew install curl aria2 w3m
	brew install bmon
	brew install siege
	brew install iftop
	brew install nmap

	## combines ping and traceroute
	brew install mtr --no-gtk

	# GNU utilities (those that come with OS X are outdated)
	brew install coreutils
	brew install binutils

	brew install ffmpeg

	# lightweight and flexible command-line JSON processor.
	brew install jq

	brew install findutils
	brew install rename tree
	brew install keychain ssh-copy-id htop-osx

	brew install pidof
	brew install ack
	brew install exiv2
	brew install imagemagick
	brew install valgrind
	brew install class-dump
	brew install testdisk
	brew install duti
	brew install https://raw.githubusercontent.com/diimdeep/OSXey/master/osxey.rb

	brew install youtube-dl

	brew install afsctool
	brew install apg

	# Remove outdated versions from the cellar
	brew cleanup
}

# Check for Homebrew
if test ! $(which brew)
then
	echo "You should probably install Homebrew first http://mxcl.github.com/homebrew/"
else
	echo "Homebrew found."
	read -p "Install formulas? (y/n) " -n 1
	echo
	if [[ $REPLY =~ ^[Yy]$ ]]; then
		installThings
		exit
	else
		exit
	fi
fi