#!/bin/bash

# pre-patched and adjusted fonts for usage with the new Powerline
# Powerline is a statusline plugin for vim, and provides statuslines and prompts for several other applications.

TDIR=`mktemp -d`

trap "{ cd - ; rm -rf $TDIR; exit 255; }" SIGINT

cd $TDIR

git clone https://github.com/powerline/fonts.git
cd fonts
./install.sh
cd -

cd -

rm -rf $TDIR

exit 0
