#!/bin/bash
git clone https://github.com/phracker/HopperScripts ~/Library/Application\ Support/Hopper/Scripts/HopperScripts && mv ~/Library/Application\ Support/Hopper/Scripts/HopperScripts/* ~/Library/Application\ Support/Hopper/Scripts/ && rm -rf ~/Library/Application\ Support/Hopper/Scripts/HopperScripts
