#!/usr/bin/env ruby

puts "Linking library ..."

DOTFILES = "~/.dotfiles"

links = [

	"osx/etc/.htoprc",

	# shell
	"osx/etc/.bashrc",
	"osx/etc/.bash_profile",
	"osx/etc/.zshrc",
	"osx/etc/.inputrc",
	"osx/logs/.bash_eternal_history",
	"osx/logs/.zsh_history",

	# git
	"osx/etc/git/.gitconfig",
	"etc/git/.gitattributes",
	"etc/git/.gitignore_global"
]

links.each	do |link|
	`ln -sFfv #{DOTFILES}/#{link} $HOME/`
end

`ln -sFfv #{DOTFILES}/etc/ssh $HOME/.ssh`